// Code generated by protoc-gen-gogo.
// source: chat.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Message
	Stream
	Channel
*/
package main

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Message struct {
	// Microseconds since epoch.
	Timestamp        *int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	PeerId           *string `protobuf:"bytes,3,opt,name=peerId" json:"peerId,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Message) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Message) GetPeerId() string {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return ""
}

func (m *Message) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// Messages published by a peer.
type Stream struct {
	Message          []*Message `protobuf:"bytes,1,rep,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}

func (m *Stream) GetMessage() []*Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Channel struct {
	Peer             []*Channel_Peer `protobuf:"bytes,1,rep,name=peer" json:"peer,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}

func (m *Channel) GetPeer() []*Channel_Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Channel_Peer struct {
	// Human-readable name.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Base58-encoded multihash.
	Id               *string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Channel_Peer) Reset()         { *m = Channel_Peer{} }
func (m *Channel_Peer) String() string { return proto.CompactTextString(m) }
func (*Channel_Peer) ProtoMessage()    {}

func (m *Channel_Peer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Channel_Peer) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func init() {
}
